const router = require('express').Router();
const c = require('../controllers/academicsController');
const { requireMinRole } = require('../middleware/auth');
const staff = requireMinRole('teacher');
const admin = requireMinRole('principal');
router.get('/classes', staff, c.getClasses);
router.post('/classes', admin, c.createClass);
router.put('/classes/:id', admin, c.updateClass);
router.get('/subjects', staff, c.getSubjects);
router.post('/subjects', admin, c.createSubject);
router.get('/exam-series', staff, c.getExamSeries);
router.post('/exam-series', admin, c.createExamSeries);
router.get('/papers/:id', staff, c.getExamPaper);
router.post('/papers/:id/marks', staff, c.saveMarks);
router.post('/papers/:id/submit', staff, c.submitPaper);
router.post('/papers/:id/approve', admin, c.approvePaper);
router.post('/papers/:id/lock', admin, c.lockPaper);
router.get('/broadsheet', staff, c.getBroadsheet);
router.get('/report-card/:studentId', staff, c.getReportCard);
module.exports = router;