const router = require('express').Router();
const c = require('../controllers/curriculumController');
const { requireMinRole } = require('../middleware/auth');
const staff = requireMinRole('teacher');
const admin = requireMinRole('principal');
router.get('/subjects', staff, c.getSubjectsByLevel);
router.post('/subjects/seed', admin, c.seedDefaultSubjects);
router.post('/subjects/select', staff, c.selectStudentSubjects);
router.get('/subjects/student/:id', staff, c.getStudentSubjects);
router.get('/cbc/strands', staff, c.getCbcStrands);
router.post('/cbc/strands', admin, c.createCbcStrand);
router.post('/cbc/marks', staff, c.enterCbcMarks);
router.get('/cbc/marks', staff, c.getCbcMarks);
router.post('/844/marks', staff, c.enter844Marks);
router.get('/844/marks', staff, c.get844Marks);
router.get('/report-card/:studentId', staff, c.getFullReportCard);
router.get('/knec-scale', staff, c.getKnecScale);
router.put('/knec-scale', admin, c.updateKnecScale);
router.get('/auto-comments', staff, c.getAutoComments);
router.post('/auto-comments', admin, c.upsertAutoComment);
router.delete('/auto-comments/:id', admin, c.deleteAutoComment);
router.get('/broadsheet', staff, c.getClassBroadsheet);
module.exports = router;