const router = require('express').Router();
const c = require('../controllers/deanController');
const { requireMinRole, requireRole } = require('../middleware/auth');
const staff = requireMinRole('teacher');
const admin = requireRole('super_admin','school_admin','principal','dean_of_studies');
router.post('/tsc/pre-validate', staff, c.preValidateTsc);
router.post('/tsc/register', admin, c.registerTeacher);
router.post('/tsc/documents/:id', admin, c.uploadVerificationDocument);
router.put('/tsc/review/:id', admin, c.reviewVerification);
router.get('/tsc/verifications', admin, c.getVerifications);
router.get('/tsc/verifications/:id', admin, c.getVerificationDetail);
router.get('/tsc/fraud-flags', admin, c.getFraudFlags);
router.put('/tsc/fraud-flags/:id', admin, c.resolveFraudFlag);
router.get('/teachers', admin, c.getTeachers);
router.post('/teachers/:id/reset-password', admin, c.resetTeacherPassword);
router.put('/teachers/:id/deactivate', admin, c.deactivateTeacher);
router.post('/discipline/incident', staff, c.reportIncident);
router.get('/discipline', admin, c.getIncidents);
router.get('/discipline/student/:id', staff, c.getStudentDisciplineHistory);
module.exports = router;