const router = require('express').Router();
const c = require('../controllers/examsController');
const { requireMinRole } = require('../middleware/auth');
const staff = requireMinRole('teacher');
const admin = requireMinRole('principal');
router.get('/series', staff, c.getExamSeries);
router.get('/series/:id', staff, c.getExamSeriesById);
router.post('/series', admin, c.createExamSeries);
router.put('/series/:id', admin, c.updateExamSeries);
router.delete('/series/:id', admin, c.deleteExamSeries);
router.get('/papers', staff, c.getExamPapers);
router.get('/papers/:id', staff, c.getPaperById);
router.get('/papers/:paperId/marks', staff, c.getPaperMarks);
router.post('/papers/:paperId/marks', staff, c.enterMarks);
router.get('/results', staff, c.getResults);
router.get('/broadsheet', staff, c.getBroadsheet);
router.get('/series/:id/results', staff, c.getResults);
router.get('/series/:id/broadsheet', staff, c.getBroadsheet);
router.get('/report-card/:studentId', staff, c.getStudentReportCard);
router.post('/series/:id/publish', admin, c.publishExamSeries);
router.post('/series/:id/lock', admin, c.lockExamSeries);
router.get('/history/:studentId', staff, c.getStudentHistory);
router.get('/grading-scale', staff, c.getGradingScalePublic);
router.post('/grading-scale', admin, c.saveGradingScale);
router.post('/marks/bulk', staff, c.bulkSaveMarks);
module.exports = router;