const router = require('express').Router();
const c = require('../controllers/libraryController');
const { requireMinRole } = require('../middleware/auth');
const lib = requireMinRole('teacher');
const admin = requireMinRole('librarian');
router.get('/books', lib, c.getBooks);
router.get('/books/:id', lib, c.getBook);
router.post('/books', admin, c.addBook);
router.put('/books/:id', admin, c.updateBook);
router.delete('/books/:id', admin, c.deleteBook);
router.get('/members', lib, c.getMembers);
router.post('/members', lib, c.registerMember);
router.get('/borrowings', lib, c.getBorrowings);
router.post('/borrowings/issue', lib, c.issueBook);
router.post('/borrowings/return', lib, c.returnBook);
router.post('/borrowings/renew', lib, c.renewBook);
router.get('/fines', lib, c.getFines);
router.post('/fines/pay', lib, c.payFine);
router.post('/fines/waive', admin, c.waiveFine);
router.post('/reservations', lib, c.reserveBook);
router.get('/stats', lib, c.getStats);
module.exports = router;