const router = require('express').Router();
const c = require('../controllers/sportsController');
const { requireMinRole } = require('../middleware/auth');
const staff = requireMinRole('teacher');
router.get('/teams', staff, c.getTeams);
router.post('/teams', staff, c.createTeam);
router.put('/teams/:id', staff, c.updateTeam);
router.get('/teams/:id/players', staff, c.getTeamPlayers);
router.post('/teams/:id/players', staff, c.addPlayerToTeam);
router.delete('/teams/:teamId/players/:playerId', staff, c.removePlayerFromTeam);
router.get('/events', staff, c.getEvents);
router.post('/events', staff, c.createEvent);
router.put('/events/:id/result', staff, c.updateEventResult);
router.get('/houses', staff, c.getHouses);
router.post('/houses', staff, c.createHouse);
router.post('/houses/:id/events', staff, c.logHouseEvent);
router.get('/stats', staff, c.getSportsStats);
router.get('/student/:id', staff, c.getStudentSports);
module.exports = router;