const router = require('express').Router();
const c = require('../controllers/staffController');
const { requireMinRole } = require('../middleware/auth');
const admin = requireMinRole('principal');
const staff = requireMinRole('teacher');
router.get('/', staff, c.getStaff);
router.get('/stats', admin, c.getStaffStats);
router.get('/:id', staff, c.getStaffMember);
router.post('/', admin, c.createStaff);
router.put('/:id', admin, c.updateStaff);
router.delete('/:id', admin, c.deleteStaff);
router.post('/:id/subjects', admin, c.assignSubjects);
module.exports = router;