const router = require('express').Router();
const c = require('../controllers/storekeeperController');
const { requireRole } = require('../middleware/auth');
const store = requireRole('super_admin','school_admin','principal','storekeeper','accounts_clerk','bursar');
const admin = requireRole('super_admin','school_admin','principal','bursar');
router.get('/categories', store, c.getCategories);
router.post('/categories', admin, c.createCategory);
router.get('/items/alerts', store, c.getLowStockAlerts);
router.get('/items/report', store, c.getStockReport);
router.get('/items', store, c.getItems);
router.get('/items/:id', store, c.getItem);
router.post('/items', admin, c.createItem);
router.put('/items/:id', admin, c.updateItem);
router.delete('/items/:id', admin, c.deleteItem);
router.get('/transactions', store, c.getTransactions);
router.post('/transactions', store, c.createTransaction);
router.get('/purchase-orders', store, c.getPurchaseOrders);
router.post('/purchase-orders', admin, c.createPurchaseOrder);
router.put('/purchase-orders/:id/approve', admin, c.approvePurchaseOrder);
router.post('/purchase-orders/:id/receive', admin, c.receivePurchaseOrder);
module.exports = router;